//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectSystemWebsite.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public string EmpID { get; set; }
        public string EmpCode { get; set; }
        public string ShifName { get; set; }
        public Nullable<int> AbsenceInShif { get; set; }
        public Nullable<int> OnPhone { get; set; }
        public Nullable<int> Chatting { get; set; }
        public Nullable<int> UseComputer { get; set; }
        public Nullable<int> SlowRepresentative { get; set; }
        public Nullable<int> CustomerComplaint { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> CreateBy { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
