//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectSystem.Web.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DirectSystemEntities : DbContext
    {
        public DirectSystemEntities()
            : base("name=DirectSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tbl_Account> tbl_Account { get; set; }
        public DbSet<tbl_CustomerBehavior> tbl_CustomerBehavior { get; set; }
        public DbSet<tbl_CustomerInfo> tbl_CustomerInfo { get; set; }
        public DbSet<tbl_Employee> tbl_Employee { get; set; }
    }
}
