//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectSystem.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CustomerInfo
    {
        public tbl_CustomerInfo()
        {
            this.tbl_CustomerBehavior = new HashSet<tbl_CustomerBehavior>();
        }
    
        public string CustomerID { get; set; }
        public string StoreCode { get; set; }
        public Nullable<int> EntryNumber { get; set; }
        public Nullable<int> ForeignNumber { get; set; }
        public Nullable<int> AgeGroup1 { get; set; }
        public Nullable<int> AgeGroup2 { get; set; }
        public Nullable<int> AgeGroup3 { get; set; }
        public Nullable<int> GenderMale { get; set; }
        public Nullable<int> GenderFemale { get; set; }
        public Nullable<int> Index_Pathway1 { get; set; }
        public Nullable<int> Index_Pathway2 { get; set; }
        public Nullable<int> Index_Pathway3 { get; set; }
        public string ShifName { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    
        public virtual ICollection<tbl_CustomerBehavior> tbl_CustomerBehavior { get; set; }
    }
}
